export const moviesActionTypes = {
    FETCH_ALL_MOVIES_REQUEST: 'FETCH_ALL_MOVIES_REQUEST',
    FETCH_ALL_MOVIES_SUCCESS: 'FETCH_ALL_MOVIES_SUCCESS',
    FETCH_ALL_MOVIES_FAILURE: 'FETCH_ALL_MOVIES_FAILURE',
    LOAD_MORE_ALL_MOVIES_SUCCESS: 'LOAD_MORE_ALL_MOVIES_SUCCESS',

    FETCH_BOOKMARKED_MOVIES_REQUEST: 'FETCH_BOOKMARKED_MOVIES_REQUEST',
    FETCH_BOOKMARKED_MOVIES_SUCCESS: 'FETCH_BOOKMARKED_MOVIES_SUCCESS',
    FETCH_BOOKMARKED_MOVIES_FAILURE: 'FETCH_BOOKMARKED_MOVIES_FAILURE',
    LOAD_MORE_BOOKMARKED_MOVIES_SUCCESS: 'LOAD_MORE_BOOKMARKED_MOVIES_SUCCESS',

    FETCH_SERIES_REQUEST: 'FETCH_SERIES_REQUEST',
    FETCH_SERIES_SUCCESS: 'FETCH_SERIES_SUCCESS',
    FETCH_SERIES_FAILURE: 'FETCH_SERIES_FAILURE',
    LOAD_MORE_SERIES_SUCCESS: 'LOAD_MORE_SERIES_SUCCESS',

    FETCH_BOOKMARKED_SERIES_REQUEST: 'FETCH_BOOKMARKED_SERIES_REQUEST',
    FETCH_BOOKMARKED_SERIES_SUCCESS: 'FETCH_BOOKMARKED_SERIES_SUCCESS',
    FETCH_BOOKMARKED_SERIES_FAILURE: 'FETCH_BOOKMARKED_SERIES_FAILURE',
    LOAD_MORE_BOOKMARKED_SERIES_SUCCESS: 'LOAD_MORE_BOOKMARKED_SERIES_SUCCESS',



    // FETCH_HORROR_MOVIES_REQUEST: 'FETCH_HORROR_MOVIES_REQUEST',
    // FETCH_HORROR_MOVIES_SUCCESS: 'FETCH_HORROR_MOVIES_SUCCESS',
    // FETCH_HORROR_MOVIES_FAILURE: 'FETCH_HORROR_MOVIES_FAILURE',
    // LOAD_MORE_HORROR_MOVIES_SUCCESS: 'LOAD_MORE_HORROR_MOVIES_SUCCESS',

    // FETCH_NETFLIX_MOVIES_REQUEST: 'FETCH_NETFLIX_MOVIES_REQUEST',
    // FETCH_NETFLIX_MOVIES_SUCCESS: 'FETCH_NETFLIX_MOVIES_SUCCESS',
    // FETCH_NETFLIX_MOVIES_FAILURE: 'FETCH_NETFLIX_MOVIES_FAILURE',
    // LOAD_MORE_NETFLIX_MOVIES_SUCCESS: 'LOAD_MORE_NETFLIX_MOVIES_SUCCESS',

    // FETCH_ROMANCE_MOVIES_REQUEST: 'FETCH_ROMANCE_MOVIES_REQUEST',
    // FETCH_ROMANCE_MOVIES_SUCCESS: 'FETCH_ROMANCE_MOVIES_SUCCESS',
    // FETCH_ROMANCE_MOVIES_FAILURE: 'FETCH_ROMANCE_MOVIES_FAILURE',
    // LOAD_MORE_ROMANCE_MOVIES_SUCCESS: 'LOAD_MORE_ROMANCE_MOVIES_SUCCESS',

    // FETCH_TOP_RATED_MOVIES_REQUEST: 'FETCH_TOP_RATED_MOVIES_REQUEST',
    // FETCH_TOP_RATED_MOVIES_SUCCESS: 'FETCH_TOP_RATED_MOVIES_SUCCESS',
    // FETCH_TOP_RATED_MOVIES_FAILURE: 'FETCH_TOP_RATED_MOVIES_FAILURE',
    // LOAD_MORE_TOP_RATED_MOVIES_SUCCESS: 'LOAD_MORE_TOP_RATED_MOVIES_SUCCESS',
    
    // FETCH_TRENDING_MOVIES_REQUEST: 'FETCH_TRENDING_MOVIES_REQUEST',
    // FETCH_TRENDING_MOVIES_SUCCESS: 'FETCH_TRENDING_MOVIES_SUCCESS',
    // FETCH_TRENDING_MOVIES_FAILURE: 'FETCH_TRENDING_MOVIES_FAILURE',
    // LOAD_MORE_TRENDING_MOVIES_SUCCESS: 'LOAD_MORE_TRENDING_MOVIES_SUCCESS',

    // FETCH_UPCOMING_MOVIES_REQUEST: 'FETCH_UPCOMING_MOVIES_REQUEST',
    // FETCH_UPCOMING_MOVIES_SUCCESS: 'FETCH_UPCOMING_MOVIES_SUCCESS',
    // FETCH_UPCOMING_MOVIES_FAILURE: 'FETCH_UPCOMING_MOVIES_FAILURE',
    // LOAD_MORE_UPCOMING_MOVIES_SUCCESS: 'LOAD_MORE_UPCOMING_MOVIES_SUCCESS',

    // FETCH_LATEST_MOVIES_REQUEST: 'FETCH_LATEST_MOVIES_REQUEST',
    // FETCH_LATEST_MOVIES_SUCCESS: 'FETCH_LATEST_MOVIES_SUCCESS',
    // FETCH_LATEST_MOVIES_FAILURE: 'FETCH_LATEST_MOVIES_FAILURE',
    // LOAD_MORE_LATEST_MOVIES_SUCCESS: 'LOAD_MORE_LATEST_MOVIES_SUCCESS'
}